// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ui7YC4h6EqwBPKArVJN7SZyOXzXG3Dc',
    appId: '1:153229951872:web:629d02e8f659436a46b765',
    messagingSenderId: '153229951872',
    projectId: 'yathrikan-mini',
    authDomain: 'yathrikan-mini.firebaseapp.com',
    storageBucket: 'yathrikan-mini.firebasestorage.app',
    measurementId: 'G-QJ70JRHKGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGRfieuFymjiPUV1GxhJgB9akS6w1H8c',
    appId: '1:153229951872:android:5494d6c467ddc40846b765',
    messagingSenderId: '153229951872',
    projectId: 'yathrikan-mini',
    storageBucket: 'yathrikan-mini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9H0mY5OkIBMskuBQ0lJuTfJhyfVowrxw',
    appId: '1:153229951872:ios:a19590b57b7144d946b765',
    messagingSenderId: '153229951872',
    projectId: 'yathrikan-mini',
    storageBucket: 'yathrikan-mini.firebasestorage.app',
    iosBundleId: 'com.example.busway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9H0mY5OkIBMskuBQ0lJuTfJhyfVowrxw',
    appId: '1:153229951872:ios:a19590b57b7144d946b765',
    messagingSenderId: '153229951872',
    projectId: 'yathrikan-mini',
    storageBucket: 'yathrikan-mini.firebasestorage.app',
    iosBundleId: 'com.example.busway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Ui7YC4h6EqwBPKArVJN7SZyOXzXG3Dc',
    appId: '1:153229951872:web:b61f20de0b156a2546b765',
    messagingSenderId: '153229951872',
    projectId: 'yathrikan-mini',
    authDomain: 'yathrikan-mini.firebaseapp.com',
    storageBucket: 'yathrikan-mini.firebasestorage.app',
    measurementId: 'G-VVMHQY66MW',
  );
}
