import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'YATHRIKAN',
      'live_buses': 'Live buses near you',
      'search_hint': 'Enter Bus Number (e.g. KL-07...)',
      'coming_soon': 'Coming Soon',

      // Home
      'home': 'Home',
      'route': 'Route',
      'profile': 'Profile',
      'arriving_in': 'Arriving in',
      'current_speed': 'Current Speed',
      'quick_actions': 'Quick Actions',
      'shortest_route': 'Shortest Route',
      'my_ticket': 'My Ticket',
      'complaint': 'Complaint',
      'safety': 'Safety',

      // Route Screen
      'routes': 'Routes',
      'routes_title': 'Routes',
      'recent_routes': 'Recent Routes',
      'favorites': 'Favorites',
      'all_routes_title': 'All Available Routes',
      'add_new': 'Add New',
      'route_planning': 'Route Planning',
      'find_best_routes': 'Find the best routes for your journey.',
      'coming_soon_desc':
          'Find the best routes for your journey.\nComing soon!',

      // Shortest Route
      'your_location': 'Your Location',
      'search_destination': 'Search destination',
      'preview': 'Preview',
      'full_map': 'Full Map ↗',
      'recent_places': 'Recent Places',
      'find_route': 'Find Route',
      'central_station': 'Central Station',
      'office_hq': 'Office HQ',

      // Ticket Validation
      'ticket_validation': 'Ticket Validation',
      'validate_ride': 'Validate your ride',
      'choose_verify_method':
          'Choose how you want to verify your ticket today.',
      'manual_entry': 'Manual Entry',
      'enter_pin_hint':
          'Enter the 6-digit PIN code from your purchase receipt.',
      'verify_ticket': 'Verify Ticket',
      'ticket_verified': 'Ticket Verified Successfully!',
      'scan_qr': 'Scan QR Code',
      'scan_qr_desc':
          'Use your camera to instantly validate your digital ticket.',
      'scan_now': 'Scan Now',
      'scan_ticket': 'Scan Ticket',
      'contact_support': 'Having trouble? Contact Support',

      // Profile
      'edit_profile': 'Edit Profile',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'help_support': 'Help & Support',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',

      // Settings
      'dark_mode': 'Dark Mode',
      'enable_dark_theme': 'Enable dark theme',
      'language': 'Language',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'about_app': 'About App',
      'receive_updates': 'Receive updates about your bus',
      'location_access': 'Location Access',
      'allow_location': 'Allow app to access location',

      // Edit Profile
      'full_name': 'Full Name',
      'email': 'Email',
      'save': 'Save',
      'profile_updated': 'Profile Updated!',

      // General
      'submit': 'Submit',
      'cancel': 'Cancel',

      // Admin Finance
      'admin_finance_title': 'Admin Finance Reports',
      'total_system_revenue': 'Total System Revenue',
      'growth': 'Growth',
      'current_month': 'Current Month',
      'last_month': 'Last Month',
      'daily_comparison': 'Daily Comparison',
      'transaction_history': 'Transaction History',
      'see_all': 'See All',
      'all_transactions': 'All Transactions',
      'success': 'Success',
      'export_report': 'Export Report',
      'report_exported': 'Report exported successfully!',
      'filter_by_date': 'Filter by date',

      // Admin Support
      'user_support': 'User Support',
      'quick_actions_title': 'QUICK ACTIONS',
      'manage_routes': 'Manage\nRoutes',
      'fleet_track': 'Fleet\nTrack',
      'finance': 'Finance',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'no_tickets_in_progress': 'No tickets in progress',
      'resolved_tickets_count': 'resolved tickets',
      'ticket_id': 'Ticket ID',
      'priority': 'Priority',
      'description': 'Description:',
      'reported_by': 'Reported By',
      'close': 'Close',
      'resolve': 'Resolve',
      'ticket_status_updated': 'Ticket status updated',
      'search_coming_soon': 'Search functionality coming soon',
      'already_on_support': 'You are already on User Support',
      'open_ticket': 'Open Ticket',

      // Days
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'ksrtc': 'KSRTC',
      'private': 'Private',

      // Safety Screen
      'status_normal': 'NORMAL',
      'status_warning': 'WARNING',
      'status_danger': 'DANGER',
      'road_condition': 'ROAD',
      'visibility': 'VISIBILITY',
      'next_stop': 'NEXT',
      'mins_away': 'mins away',
      'searching': 'Searching...',
      'calculating': 'Calculating...',
      'emergency_services': 'Emergency Services',
      'police_control': 'Police Control Room',
      'fire_force': 'Fire Force',
      'ambulance': 'Ambulance',
      'women_helpline': 'Women Helpline',
      'child_helpline': 'Child Helpline',
      'general_emergency': 'General Emergency (112)',
      'report_issue_title': 'Report Issue',
      'report_issue_subtitle': 'Reckless driving, hazards',
      'emergency_contacts_title': 'Emergency Contacts',
      'emergency_contacts_subtitle': 'Police, Ambulance, Fire, Helplines',

      // Complaint Screen
      'file_complaint': 'File a Complaint',
      'what_went_wrong': 'What went wrong?',
      'complaint_desc': 'We\'re sorry you had a bad experience. Please share the details so we can improve.',
      'bus_number_label': 'Bus Number',
      'issue_category': 'Issue Category',
      'select_category': 'Select a category',
      'complaint_details_label': 'Description',
      'complaint_details_hint': 'Tell us more details about what happened...',
      'add_evidence': 'Add Evidence',
      'optional': '(Optional)',
      'add_media': 'ADD MEDIA',
      'submit_complaint': 'Submit Complaint',

      // Routes Screen
      'popular_routes': 'Popular Routes',
      'trending': 'Trending',
      'fastest': 'Fastest',
      'every_min': 'Every',
      'live_map_preview': 'Live Map Preview',

      // Notifications
      'clear_all': 'Clear All',
      'no_notifications': 'No new notifications',
      'bus_arriving_soon': 'Bus Arriving Soon',
      'bus_arriving_message': 'The bus is approaching your stop.',
      'ticket_confirmed': 'Ticket Confirmed',
      'ticket_confirmed_message': 'Your ticket has been successfully booked.',
      'welcome_title': 'Welcome to Yathrikan',
      'welcome_message': 'Thank you for installing the app.',
      'just_now': 'Just now',
      'hours_ago': 'hours ago',
      'day_ago': '1 day ago',

      // Common
      'loading': 'Loading...',
      'unknown': 'Unknown',
      'good_visibility': 'Good visibility',
      'moderate_visibility': 'Moderate visibility',
      'dry': 'Dry',

      // Push Notifications
      'push_bus_here_title': '🚌 {0} is here!',
      'push_bus_here_body': '{0} → {1} | {2} arrived at {3}. Board now!',
      'push_bus_warning_title': '⏱ {0} arriving in ~1 min!',
      'push_bus_warning_body': '{0} → {1} | Get ready to board at {2}.',

      // Generic
      'Now': 'Now',
      'incoming_buses': 'Incoming Buses',
      'no_incoming_buses': 'No incoming buses found. Tap \'Find Route\' to search.',
      'eta': 'ETA',
      'done': 'Done',
      'edit': 'Edit',
      'mins_ago': 'mins ago',
      'yesterday': 'Yesterday',
      'days_ago': 'days ago',
      'last_viewed': 'Last viewed',
      'min': 'min',
      'Live': 'Live',
      'Scheduled': 'Scheduled',
      'N/A': 'N/A',
      'Var': 'Var',
      'Current Location': 'Current Location',
      'current location': 'current location',
      'your location': 'your location',
      'from': 'from',
      'to': 'to',
      'min_short': 'm',
      'active': 'Active',
      'open_map': 'Open Map',
      'buses_active_nearby': 'Buses Active Nearby',
      
      // We do not need to populate 100+ English places because translate() defaults to the key if not found.
    },
    'ml': {
      'app_title': 'യാത്രികൻ',
      'live_buses': 'നിങ്ങളുടെ അടുത്തുള്ള തത്സമയ ബസുകൾ',
      'search_hint': 'ബസ് നമ്പർ നൽകുക (ഉദാഹരണത്തിന് KL-07...)',
      'coming_soon': 'ഉടൻ വരുന്നു',

      // Home
      'home': 'ഹോം',
      'route': 'റൂട്ട്',
      'profile': 'പ്രൊഫൈൽ',
      'arriving_in': 'എത്താൻ സമയം',
      'current_speed': 'നിലവിലെ വേഗത',
      'quick_actions': 'സേവനങ്ങൾ',
      'shortest_route': 'റൂട്ട് കണ്ടെത്തുക',
      'my_ticket': 'ടിക്കറ്റ്',
      'complaint': 'പരാതി',
      'safety': 'സുരക്ഷ',

      // Route Screen
      'routes': 'റൂട്ടുകൾ',
      'routes_title': 'റൂട്ടുകൾ',
      'recent_routes': 'അടുത്തിടെ നോക്കിയവ',
      'favorites': 'പ്രിയപ്പെട്ടവ',
      'all_routes_title': 'ലഭ്യമായ എല്ലാ റൂട്ടുകളും',
      'add_new': 'പുതിയത് ചേർക്കുക',
      'route_planning': 'റൂട്ട് പ്ലാനിംഗ്',
      'find_best_routes':
          'നിങ്ങളുടെ യാത്രയ്ക്കുള്ള മികച്ച റൂട്ടുകൾ കണ്ടെത്തുക.',
      'coming_soon_desc':
          'നിങ്ങളുടെ യാത്രയ്ക്കുള്ള മികച്ച റൂട്ടുകൾ കണ്ടെത്തുക.\nഉടൻ വരുന്നു!',

      // Shortest Route
      'your_location': 'നിങ്ങളുടെ സ്ഥലം',
      'search_destination': 'ലക്ഷ്യസ്ഥാനം തിരയുക',
      'preview': 'പ്രിവ്യൂ',
      'full_map': 'പൂർണ്ണ മാപ്പ് ↗',
      'recent_places': 'അടുത്തിടെ സന്ദർശിച്ച സ്ഥലങ്ങൾ',
      'find_route': 'റൂട്ട് കണ്ടെത്തുക',
      'central_station': 'സെൻട്രൽ സ്റ്റേഷൻ',
      'office_hq': 'ഓഫീസ് ആസ്ഥാനം',

      // Ticket Validation
      'ticket_validation': 'ടിക്കറ്റ് പരിശോധന',
      'validate_ride': 'നിങ്ങളുടെ യാത്ര സാധൂകരിക്കുക',
      'choose_verify_method':
          'ടിക്കറ്റ് പരിശോധിക്കാൻ ഒരു മാർഗ്ഗം തിരഞ്ഞെടുക്കുക.',
      'manual_entry': 'മാന്വൽ എൻട്രി',
      'enter_pin_hint': 'രസീതിലെ 6 അക്ക PIN കോഡ് നൽകുക.',
      'verify_ticket': 'ടിക്കറ്റ് പരിശോധിക്കുക',
      'ticket_verified': 'ടിക്കറ്റ് വിജയകരമായി പരിശോധിച്ചു!',
      'scan_qr': 'QR കോഡ് സ്കാൻ ചെയ്യുക',
      'scan_qr_desc': 'ക്യാമറ ഉപയോഗിച്ച് ടിക്കറ്റ് പരിശോധിക്കുക.',
      'scan_now': 'ഇപ്പോൾ സ്കാൻ ചെയ്യുക',
      'scan_ticket': 'ടിക്കറ്റ് സ്കാൻ',
      'contact_support': 'സഹായം ആവശ്യമുണ്ടോ? സപ്പോർട്ടുമായി ബന്ധപ്പെടുക',

      // Profile
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'notifications': 'അറിയിപ്പുകൾ',
      'settings': 'സജ്ജീകരണങ്ങൾ',
      'help_support': 'സഹായം',
      'logout': 'ലോഗ് ഔട്ട്',
      'logout_confirm': 'ലോഗ് ഔട്ട് ചെയ്യണോ?',

      // Settings
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'enable_dark_theme': 'ഡാർക്ക് തീം പ്രവർത്തനക്ഷമമാക്കുക',
      'language': 'ഭാഷ',
      'privacy_policy': 'സ്വകാര്യതാ നയം',
      'terms_of_service': 'സേവന വ്യവസ്ഥകൾ',
      'about_app': 'ആപ്പിനെക്കുറിച്ച്',
      'receive_updates': 'ബസ് അറിയിപ്പുകൾ ലഭിക്കുക',
      'location_access': 'ലൊക്കേഷൻ',
      'allow_location': 'ലൊക്കേഷൻ അനുവദിക്കുക',

      // Edit Profile
      'full_name': 'പേര്',
      'email': 'ഇമെയിൽ',
      'save': 'സേവ് ചെയ്യുക',
      'profile_updated': 'പ്രൊഫൈൽ അപ്‌ഡേറ്റ് ചെയ്തു!',

      // General
      'submit': 'സമർപ്പിക്കുക',
      'cancel': 'റദ്ദാക്കുക',

      // Admin Finance
      'admin_finance_title': 'അഡ്മിൻ ഫിനാൻസ് റിപ്പോർട്ടുകൾ',
      'total_system_revenue': 'മൊത്തം വരുമാനം',
      'growth': 'വളർച്ച',
      'current_month': 'ഈ മാസം',
      'last_month': 'കഴിഞ്ഞ മാസം',
      'daily_comparison': 'ദിവസേനയുള്ള താരതമ്യം',
      'transaction_history': 'ഇടപാട് ചരിത്രം',
      'see_all': 'എല്ലാം കാണുക',
      'all_transactions': 'എല്ലാ ഇടപാടുകളും',
      'success': 'വിജയിച്ചു',
      'export_report': 'റിപ്പോർട്ട് എക്സ്പോർട്ട് ചെയ്യുക',
      'report_exported': 'റിപ്പോർട്ട് വിജയകരമായി എക്സ്പോർട്ട് ചെയ്തു!',
      'filter_by_date': 'തീയതി പ്രകാരം ഫിൽട്ടർ ചെയ്യുക',

      // Admin Support
      'user_support': 'ഉപഭോക്തൃ സഹായം',
      'quick_actions_title': 'സേവനങ്ങൾ',
      'manage_routes': 'റൂട്ടുകൾ\nനിയന്ത്രിക്കുക',
      'fleet_track': 'ഫ്ലീറ്റ്\nട്രാക്ക്',
      'finance': 'ഫിനാൻസ്',
      'pending': 'തീർപ്പുകൽപ്പിക്കാത്തവ',
      'in_progress': 'പുരോഗമിക്കുന്നു',
      'resolved': 'പരിഹരിച്ചവ',
      'no_tickets_in_progress': 'പുരോഗതിയിലുള്ള ടിക്കറ്റുകളില്ല',
      'resolved_tickets_count': 'പരിഹരിച്ച ടിക്കറ്റുകൾ',
      'ticket_id': 'ടിക്കറ്റ് ഐഡി',
      'priority': 'മുൻഗണന',
      'description': 'വിവരണം:',
      'reported_by': 'റിപ്പോർട്ട് ചെയ്തത്',
      'close': 'അടയ്ക്കുക',
      'resolve': 'പരിഹരിക്കുക',
      'ticket_status_updated': 'ടിക്കറ്റ് നില അപ്‌ഡേറ്റുചെയ്‌തു',
      'search_coming_soon': 'തിരയൽ ഉടൻ വരുന്നു',
      'already_on_support': 'നിങ്ങൾ ഇതിനകം തന്നെ ഉപഭോക്തൃ സഹായത്തിലാണ്',
      'open_ticket': 'ടിക്കറ്റ് തുറക്കുക',

      // Days
      'mon': 'തിങ്കൾ',
      'tue': 'ചൊവ്വ',
      'wed': 'ബുധൻ',
      'thu': 'വ്യാഴം',
      'fri': 'വെള്ളി',
      'sat': 'ശനി',
      'sun': 'ഞായർ',
      'ksrtc': 'കെഎസ്ആർടിസി',
      'private': 'സ്വകാര്യം',

      // Safety Screen
      'status_normal': 'സാധാരണ',
      'status_warning': 'മുന്നറിയിപ്പ്',
      'status_danger': 'അപകടം',
      'road_condition': 'റോഡ്',
      'visibility': 'കാഴ്ച',
      'next_stop': 'അടുത്തത്',
      'mins_away': 'മിനിറ്റിനുള്ളിൽ',
      'searching': 'തിരയുന്നു...',
      'calculating': 'കണക്കാക്കുന്നു...',
      'emergency_services': 'അടിയന്തര സേവനങ്ങൾ',
      'police_control': 'പ്പോലീസ് കൺട്രോൾ റൂം',
      'fire_force': 'ഫയർ ഫോഴ്സ്',
      'ambulance': 'ആംബുലൻസ്',
      'women_helpline': 'വനിതാ ഹെൽപ്പ് ലൈൻ',
      'child_helpline': 'ചൈൽഡ് ഹെൽപ്പ് ലൈൻ',
      'general_emergency': 'പൊതു അടിയന്തര സഹായം (112)',
      'report_issue_title': 'പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
      'report_issue_subtitle': 'അശ്രദ്ധമായ ഡ്രൈവിംഗ്, അപകടങ്ങൾ',
      'emergency_contacts_title': 'അടിയന്തര കോൺടാക്റ്റുകൾ',
      'emergency_contacts_subtitle': 'പ്പോലീസ്, ആംബുലൻസ്, ഫയർ, ഹെൽപ്പ് ലൈനുകൾ',

      // Complaint Screen
      'file_complaint': 'പരാതി നൽകുക',
      'what_went_wrong': 'എന്താണ് സംഭവിച്ചത്?',
      'complaint_desc': 'നിങ്ങൾക്കുണ്ടായ മോശം അനുഭവത്തിൽ ഞങ്ങൾ ഖേദിക്കുന്നു. മെച്ചപ്പെടുത്താൻ ഞങ്ങളെ സഹായിക്കൂ.',
      'bus_number_label': 'ബസ് നമ്പർ',
      'issue_category': 'പരാതി വിഭാഗം',
      'select_category': 'ഒരു വിഭാഗം തിരഞ്ഞെടുക്കുക',
      'complaint_details_label': 'വിവരണം',
      'complaint_details_hint': 'എന്താണ് സംഭവിച്ചതെന്ന് കൂടുതൽ വിവരങ്ങൾ നൽകുക...',
      'add_evidence': 'തെളിവ് ചേർക്കുക',
      'optional': '(ഓപ്ഷണൽ)',
      'add_media': 'മീഡിയ ചേർക്കുക',
      'submit_complaint': 'പരാതി സമർപ്പിക്കുക',

      // Routes Screen
      'popular_routes': 'ജനപ്രിയ റൂട്ടുകൾ',
      'trending': 'ട്രെൻഡിംഗ്',
      'fastest': 'വേഗമേറിയത്',
      'every_min': 'ഓരോ',
      'live_map_preview': 'തത്സമയ മാപ്പ്',

      // Notifications
      'clear_all': 'എല്ലാം മായ്ക്കുക',
      'no_notifications': 'പുതിയ അറിയിപ്പുകളില്ല',
      'bus_arriving_soon': 'ബസ് ഉടൻ എത്തും',
      'bus_arriving_message': 'ബസ് നിങ്ങളുടെ സ്റ്റോപ്പിനടുത്തെത്തി.',
      'ticket_confirmed': 'ടിക്കറ്റ് സ്ഥിരീകരിച്ചു',
      'ticket_confirmed_message': 'നിങ്ങളുടെ ടിക്കറ്റ് വിജയകരമായി ബുക്ക് ചെയ്തു.',
      'welcome_title': 'യാത്രികനിലേക്ക് സ്വാഗതം',
      'welcome_message': 'ആപ്പ് ഇൻസ്റ്റാൾ ചെയ്തതിന് നന്ദി.',
      'just_now': 'ഇപ്പോൾ',
      'hours_ago': 'മണിക്കൂർ മുമ്പ്',
      'day_ago': '1 ദിവസം മുമ്പ്',

      // Common
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'unknown': 'അജ്ഞാതം',
      'good_visibility': 'നല്ല കാഴ്ച',
      'moderate_visibility': 'മിതമായ കാഴ്ച',
      'dry': 'വരണ്ട',

      // Push Notifications
      'push_bus_here_title': '🚌 {0} എത്തിയിരിക്കുന്നു!',
      'push_bus_here_body': '{0} → {1} | {2} {3}-ൽ എത്തിയിരിക്കുന്നു. വേഗം കയറൂ!',
      'push_bus_warning_title': '⏱ {0} ~1 മിനിറ്റിനുള്ളിൽ എത്തും!',
      'push_bus_warning_body': '{0} → {1} | {2}-ൽ ബോർഡ് ചെയ്യാൻ തയ്യാറാകൂ.',

      // Generic
      'Now': 'ഇപ്പോൾ',
      'incoming_buses': 'വരുന്ന ബസുകൾ',
      'no_incoming_buses': 'ബസുകളൊന്നും കണ്ടെത്തിയില്ല. തിരയാൻ \'റൂട്ട് കണ്ടെത്തുക\' ടാപ്പുചെയ്യുക.',
      'eta': 'എത്താൻ സമയം',
      'done': 'പൂർത്തിയായി',
      'edit': 'എഡിറ്റ്',
      'mins_ago': 'മിനിറ്റുകൾക്ക് മുമ്പ്',
      'yesterday': 'ഇന്നലെ',
      'days_ago': 'ദിവസങ്ങൾക്ക് മുമ്പ്',
      'last_viewed': 'അവസാനം കണ്ടത്',
      'min': 'മിനിറ്റ്',
      'Live': 'തത്സമയം',
      'Scheduled': 'ഷെഡ്യൂൾ ചെയ്തു',
      'N/A': 'ലഭ്യമല്ല',
      'Var': 'മാറാം',
      'Current Location': 'നിലവിലെ സ്ഥലം',
      'current location': 'നിലവിലെ സ്ഥലം',
      'your location': 'നിങ്ങളുടെ സ്ഥലം',
      'from': 'ഇവിടെ നിന്ന്',
      'to': 'ഇവിടേക്ക്',
      'min_short': 'മി',
      'active': 'സജീവമാണ്',
      'open_map': 'മാപ്പ് കാണുക',
      'buses_active_nearby': 'ബസുകൾ സമീപത്തുണ്ട്',

      // Places
      'Kottayam': 'കോട്ടയം',
      'Changanassery': 'ചങ്ങനാശ്ശേരി',
      'Pala': 'പാലാ',
      'Ettumanoor': 'ഏറ്റുമാനൂർ',
      'Kanjirappally': 'കാഞ്ഞിരപ്പള്ളി',
      'Manimala': 'മണിമല',
      'Pampady': 'പാമ്പാടി',
      'Puthuppally': 'പുതുപ്പള്ളി',
      'Ayarkunnam': 'അയർക്കുന്നം',
      'Kuravilangad': 'കുറവിലങ്ങാട്',
      'Uzhavoor': 'ഉഴവൂർ',
      'Ramapuram': 'രാമപുരം',
      'Erattupetta': 'ഈരാറ്റുപേട്ട',
      'Mundakayam': 'മുണ്ടക്കയം',
      'Erumely': 'എരുമേലി',
      'Erumely North': 'എരുമേലി നോർത്ത്',
      'Vaikom': 'വൈക്കം',
      'Thalayolaparambu': 'തലയോലപ്പറമ്പ്',
      'Kaduthuruthy': 'കടുത്തുരുത്തി',
      'Kumarakom': 'കുമരകം',
      'Chingavanam': 'ചിങ്ങവനം',
      'Karukachal': 'കറുകച്ചാൽ',
      'Ponkunnam': 'പൊൻകുന്നം',
      'Manarcadu': 'മണർകാട്',
      'Kidangoor': 'കിടങ്ങൂർ',
      'Athirampuzha': 'അതിരമ്പുഴ',
      'Thazhathangady': 'താഴത്തങ്ങാടി',
      'Thiruvarppu': 'തിരുവാർപ്പ്',
      'Kottayam Railway Station': 'കോട്ടയം റെയിൽവേ സ്റ്റേഷൻ',
      'Medical College Kottayam': 'മെഡിക്കൽ കോളേജ് കോട്ടയം',
      'Koovappally': 'കൂവപ്പള്ളി',
      'Vazhoor': 'വാഴൂർ',
      'Amal Jyothi': 'അമൽ ജ്യോതി',
      'Koruthodu': 'കോരുത്തോട്',
      '14th Mile': '14-ാം മൈൽ',
      'Mannathipara': 'മണ്ണാത്തിപ്പാറ',
      'Chennampally': 'ചേന്നംപള്ളി',
      'Vakathanam': 'വാകത്താനം',
      'Kodungoor': 'കൊടുങ്ങൂർ',
      'Bharananganam': 'ഭരണങ്ങാനം',
      'Chengalam': 'ചെങ്ങളം',
      'Neendoor': 'നീണ്ടൂർ',
      'Nattakom': 'നാട്ടകം',
      'Panachikkad': 'പനച്ചിക്കാട്',
      'Thirunakkara': 'തിരുനക്കര',
      'Vechoor': 'വെച്ചൂർ',
      'Poovanthuruthu': 'പൂവന്തുരുത്ത്',
      'Melukavu': 'മേലുകാവ്',
      'Ilaveezhapoonchira': 'ഇലവീഴാപൂഞ്ചിറ',
      'Lalam': 'ളാലം',
      'Cherpunkal': 'ചേർപ്പുങ്കൽ',
      'Kuruvamoozhi': 'കുരുവമുഴി',
      'Tiruvalla': 'തിരുവല്ല',
      'Adoor': 'അടൂർ',
      'Pandalam': 'പന്തളം',
      'Ranni': 'റാന്നി',
      'Konni': 'കോന്നി',
      'Kozhencherry': 'കോഴഞ്ചേരി',
      'Mallappally': 'മല്ലപ്പള്ളി',
      'Aranmula': 'ആറന്മുള',
      'Sabarimala': 'ശബരിമല',
      'Pamba': 'പമ്പ',
      'Pathanamthitta': 'പത്തനംതിട്ട',
      'Thodupuzha': 'തൊടുപുഴ',
      'Munnar': 'മൂന്നാർ',
      'Adimali': 'അടിമാലി',
      'Kattappana': 'കട്ടപ്പന',
      'Kumily': 'കുമളി',
      'Peermade': 'പീരുമേട്',
      'Vagamon': 'വാഗമൺ',
      'Thekkady': 'തേക്കടി',
      'Nedumkandam': 'നെടുങ്കണ്ടം',
      'Rajakkad': 'രാജാക്കാട്',
      'Cheruthoni': 'ചെറുതോണി',
      'Painavu': 'പൈനാവ്',
      'Cherthala': 'ചേർത്തല',
      'Kayamkulam': 'കായംകുളം',
      'Mavelikkara': 'മാവേലിക്കര',
      'Chengannur': 'ചെങ്ങന്നൂർ',
      'Haripad': 'ഹരിപ്പാട്',
      'Ambalapuzha': 'അമ്പലപ്പുഴ',
      'Edathua': 'എടത്വ',
      'Kuttanad': 'കുട്ടനാട്',
      'Mannar': 'മാന്നാർ',
      'Punalur': 'പുനലൂർ',
      'Karunagappally': 'കരുനാഗപ്പള്ളി',
      'Paravur': 'പരവൂർ',
      'Kottarakkara': 'കൊട്ടാരക്കര',
      'Chathannoor': 'ചാത്തന്നൂർ',
      'Oachira': 'ഓച്ചിറ',
      'Anchal': 'അഞ്ചൽ',
      'Pathanapuram': 'പത്തനാപുരം',
      'Thiruvananthapuram': 'തിരുവനന്തപുരം',
      'Kollam': 'കൊല്ലം',
      'Alappuzha': 'ആലപ്പുഴ',
      'Idukki': 'ഇടുക്കി',
      'Ernakulam': 'എറണാകുളം',
      'Thrissur': 'തൃശൂർ',
      'Palakkad': 'പാലക്കാട്',
      'Malappuram': 'മലപ്പുറം',
      'Kozhikode': 'കോഴിക്കോട്',
      'Wayanad': 'വയനാട്',
      'Kannur': 'കണ്ണൂർ',
      'Kasaragod': 'കാസർഗോഡ്',
      'Kochi': 'കൊച്ചി',
      'Calicut': 'കോഴിക്കോട്',
      'Trivandrum': 'തിരുവനന്തപുരം',
      'Alleppey': 'ആലപ്പുഴ',
      'Cochin': 'കൊച്ചി',
      'Aluva': 'ആലുവ',
      'Angamaly': 'അങ്കമാലി',
      'Perumbavoor': 'പെരുമ്പാവൂർ',
      'Muvattupuzha': 'മൂവാറ്റുപുഴ',
      'Kothamangalam': 'കോതമംഗലം',
      'North Paravur': 'നോർത്ത് പറവൂർ',
      'Kalamassery': 'കളമശ്ശേരി',
      'Tripunithura': 'തൃപ്പൂണിത്തുറ',
      'Vypin': 'വൈപ്പിൻ',
      'Fort Kochi': 'ഫോർട്ട് കൊച്ചി',
      'Edappally': 'ഇടപ്പള്ളി',
      'Kaloor': 'കലൂർ',
      'Vyttila': 'വൈറ്റില',
      'Palarivattom': 'പാലാരിവട്ടം',
      'Kakkanad': 'കാക്കനാട്',
      'Marine Drive': 'മറൈൻ ഡ്രൈവ്',
      'Lulu Mall': 'ലുലു മാൾ',
      'MG Road': 'എം.ജി റോഡ്',
      'Menaka': 'മേനക',
      'Thevara': 'തേവര',
      'Thoppumpady': 'തോപ്പുംപടി',
      'Mattancherry': 'മട്ടാഞ്ചേരി',
      'Chalakudy': 'ചാലക്കുടി',
      'Kodungallur': 'കൊടുങ്ങല്ലൂർ',
      'Guruvayur': 'ഗുരുവായൂർ',
      'Kunnamkulam': 'കുന്നംകുളം',
      'Irinjalakuda': 'ഇരിങ്ങാലക്കുട',
      'Wadakkanchery': 'വടക്കാഞ്ചേരി',
      'Chavakkad': 'ചാവക്കാട്',
      'Koratty': 'കൊരട്ടി',
      'Mannuthy': 'മണ്ണുത്തി',
      'Puthukkad': 'പുതുക്കാട്',
      'Shoranur': 'ഷൊർണൂർ',
      'Ottapalam': 'ഒറ്റപ്പാലം',
      'Chittur': 'ചിറ്റൂർ',
      'Mannarkkad': 'മണ്ണാർക്കാട്',
      'Pattambi': 'പട്ടാമ്പി',
      'Cherpulassery': 'ചെർപ്പുളശ്ശേരി',
      'Alathur': 'ആലത്തൂർ',
      'Vadakkencherry': 'വടക്കഞ്ചേരി',
      'Manjeri': 'മഞ്ചേരി',
      'Perinthalmanna': 'പെരിന്തൽമണ്ണ',
      'Tirur': 'തിരൂർ',
      'Ponnani': 'പൊന്നാനി',
      'Nilambur': 'നിലമ്പൂർ',
      'Kondotty': 'കൊണ്ടോട്ടി',
      'Kottakkal': 'കോട്ടക്കൽ',
      'Valanchery': 'വളാഞ്ചേരി',
      'Vadakara': 'വടകര',
      'Koyilandy': 'കൊയിലാണ്ടി',
      'Thamarassery': 'താമരശ്ശേരി',
      'Mukkam': 'മുക്കം',
      'Ramanattukara': 'രാമനാട്ടുകര',
      'Feroke': 'ഫറോക്ക്',
      'Beypore': 'ബേപ്പൂർ',
      'Kunnamangalam': 'കുന്നമംഗലം',
      'Thazhathuvadakara': 'താഴത്തുവടകര',
      'Kalpetta': 'കൽപ്പറ്റ',
      'Sulthan Bathery': 'സുൽത്താൻ ബത്തേരി',
      'Mananthavady': 'മാനന്തവാടി',
      'Vythiri': 'വൈത്തിരി',
      'Meppadi': 'മേപ്പാടി',
      'Thalassery': 'തലശ്ശേരി',
      'Taliparamba': 'തളിപ്പറമ്പ്',
      'Payyannur': 'പയ്യന്നൂർ',
      'Mattannur': 'മട്ടന്നൂർ',
      'Iritty': 'ഇരിട്ടി',
      'Kuthuparamba': 'കൂത്തുപറമ്പ്',
      'Dharmadam': 'ധർമ്മടം',
      'Kanhangad': 'കാഞ്ഞങ്ങാട്',
      'Uppala': 'ഉപ്പള',
      'Nileshwaram': 'നീലേശ്വരം',
      'Manjeshwar': 'മഞ്ചേശ്വർ',
      'Cheruvathur': 'ചെറുവത്തൂർ',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String operator [](String key) => translate(key);
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ml'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return Future.value(AppLocalizations(locale));
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
